# NOTE: Update and uncomment: `keystore`, `password`, and `unlock` fields.

chain = "mainnet"
# identity = "node_name"
# verbosity = 3
datadir = "/var/lib/bor/data"
# ancient = ""
# keystore = "$BOR_DIR/keystore"
syncmode = "full"
# gcmode = "full"
# snapshot = true
# ethstats = ""

# ["eth.requiredblocks"]

[p2p]
    maxpeers = 1
    port = 30303
    nodiscover = true
    # maxpendpeers = 50
    # bind = "0.0.0.0"
    # nat = "any"
    # [p2p.discovery]
        # v5disc = false
        # bootnodes = []
        # bootnodesv4 = []
        # bootnodesv5 = []
        # static-nodes = []
        # trusted-nodes = []
        # dns = []

# [heimdall]
    # url = "http://localhost:1317"
    # "bor.without" = false
    # grpc-address = ""

[txpool]
    nolocals = true
    pricelimit = 30000000000
    accountslots = 16
    globalslots = 32768
    accountqueue = 16
    globalqueue = 32768
    lifetime = "1h30m0s"
    # locals = []
    # journal = ""
    # rejournal = "1h0m0s"
    # pricebump = 10

[miner]
    mine = true
    gaslimit = 30000000
    gasprice = "30000000000"
    # etherbase = ""
    # extradata = ""

[jsonrpc]
    ipcpath = "/var/lib/bor/bor.ipc"
    # ipcdisable = false
    # gascap = 50000000
    # txfeecap = 5.0
    [jsonrpc.http]
        enabled = true
        port = 8545
        host = "127.0.0.1"
        api = ["eth", "net", "web3", "txpool", "bor"]
        vhosts = ["*"]
        corsdomain = ["*"]
        # prefix = ""
    # [jsonrpc.ws]
        # enabled = false
        # port = 8546
        # prefix = ""
        # host = "localhost"
        # api = ["web3", "net"]
        # origins = ["*"]
    # [jsonrpc.graphql]
        # enabled = false
        # port = 0
        # prefix = ""
        # host = ""
        # vhosts = ["*"]
        # corsdomain = ["*"]
    # [jsonrpc.timeouts]
        # read = "30s"
        # write = "30s"
        # idle = "2m0s"

[gpo]
    # blocks = 20
    # percentile = 60
    # maxprice = "5000000000000"
    ignoreprice = "30000000000"

[telemetry]
    metrics = true
    # expensive = false
    # prometheus-addr = ""
    # opencollector-endpoint = ""
    # [telemetry.influx]
        # influxdb = false
        # endpoint = ""
        # database = ""
        # username = ""
        # password = ""
        # influxdbv2 = false
        # token = ""
        # bucket = ""
        # organization = ""
    # [telemetry.influx.tags]

[cache]
    cache = 4096
    # gc = 25
    # snapshot = 10
    # database = 50
    # trie = 15
    # journal = "triecache"
    # rejournal = "1h0m0s"
    # noprefetch = false
    # preimages = false
    # txlookuplimit = 2350000
    # timeout = "1h0m0s"

[accounts]
    allow-insecure-unlock = true
    # password = "$BOR_DIR/password.txt"
    # unlock = ["$ADDRESS"]
    # lightkdf = false
    # disable-bor-wallet = false

# [grpc]
    # addr = ":3131"

# [developer]
    # dev = false
    # period = 0
