version: '3.3'
services:
    el:
        container_name: pow-node
        image: linked0/poohnet-pow:latest
        ports:
            - "8545:8545"
            - "30303:30303"
            - "30303:30303/udp"
            - "6060:6060"
        restart: always
        volumes:
            - $HOME/.pooh/el:/data
            - ./config/el:/config
        command:
            --datadir=/data
            --syncmode=full
            --networkid=12301
            --bootnodes="enode://6d59a1ce195d9251e8f5234b3dbd486cf15eeac6cb8199898af3e11b9b7f5c54e334317d1cc3ab8077360383bc08b8aa93299ccb169b55dbea59414847dbce2d@13.209.149.243:30303"
            --allow-insecure-unlock=true
            --unlock=0x997c277946420aff5ded06d0f52725b17fa1971a
            --password=/config/password.txt
            --mine=true
            --metrics
            --metrics.addr=0.0.0.0
            --metrics.port=6060
            --miner.etherbase=0x997c277946420aff5ded06d0f52725b17fa1971a
            --http
            --http.addr="0.0.0.0"
            --http.port=8545
            --http.corsdomain="*"
            --http.api="eth,net,txpool,web3"
            --http.vhosts="*"
            --ws
            --ws.port=8546
            --ws.api="eth,net,txpool,web3"
            --ws.origins="*"
