repository: ethereum/go-ethereum

theme: minima

keep_files:
  - static

favicon: /static/images/favicon.png

defaults:
  - scope:
      path: ""
    values:
      layout: sidebar
  - scope:
      path: "*"
    values:
      root: "."
  - scope:
      path: "*/*"
    values:
      root: ".."

default_root: ".."

collections_dir: docs
collections:
  install-and-build:
    output: true
    caption: Install and build
    sidebar_index: 1
    frontpage: _install-and-build/Installing-Geth.md
  interface:
    output: true  
    caption: Interacting with Geth
    sidebar_index: 2
  support:
    output: true
    caption: Issues and support
    sidebar_index: 3
  developers:
    output: true
    caption: Developer docs
    sidebar_index: 4
  clef:
    output: true
    caption: Clef
    sidebar_index: 5
    frontpage: _clef/Overview.md
  whisper:
    output: true
    caption: Whisper
    sidebar_index: 6
    frontpage: _whisper/Whisper-Overview.md
  swarm:
    output: true
    caption: Swarm
    sidebar_index: 7
  doc:
    output: true
    caption: Other
    sidebar_index: 8
  legacy:
    output: true
    caption: Legacy content
    sidebar_index: 9



