repository: ethereum/go-ethereum

exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore

favicon: /static/images/favicon.png

defaults:
  -
    scope:
      path: ""
    values:
      layout: sidebar

collections_dir: docs
collections:
  install-and-build:
    output: true
    caption: Install and build
    sidebar_index: 1
  how-to:
    output: true
    caption: How to use
    sidebar_index: 2
  interface:
    output: true
    caption: Interface documentation
    sidebar_index: 3
  support:
    output: true
    caption: Issues and support
    sidebar_index: 4
  developers:
    output: true
    caption: Developers
    sidebar_index: 5
  doc:
    output: true
    caption: Other
    sidebar_index: 6
