[Eth]
NetworkId = 2147483647
SyncMode = "fast"
LightPeers = 100
DatabaseCache = 768
Etherbase = "0x43ec6d0942f7faef069f7f63d0384a27f529b062"
GasPrice = 18000000000
EnablePreimageRecording = false

[Eth.Ethash]
CacheDir = "ethash"
CachesInMem = 2
CachesOnDisk = 3
DatasetDir = "./privatenet/.ethash"
DatasetsInMem = 1
DatasetsOnDisk = 2
PowMode = 0

[Eth.TxPool]
NoLocals = false
Journal = "transactions.rlp"
Rejournal = 3600000000000
PriceLimit = 1
PriceBump = 10
AccountSlots = 16
GlobalSlots = 4096
AccountQueue = 64
GlobalQueue = 1024
Lifetime = 10800000000000

[Eth.GPO]
Blocks = 20
Percentile = 60

[Shh]
MaxMessageSize = 1048576
MinimumAcceptedPOW = 2e-01

[Node]
UserIdent = "ShyftTestnetNode"
DataDir = "shyftData"
KeyStoreDir = "."
IPCPath = "geth.ipc"
HTTPHost = "127.0.0.1"
HTTPPort = 8545
HTTPCors = ["*"]
HTTPVirtualHosts = ["localhost"]
HTTPModules = ["net", "web3", "eth", "shh", "admin", "debug"]
WSPort = 8546
WSModules = ["net", "web3", "eth", "shh"]

[Node.P2P]
MaxPeers = 25
NoDiscovery = false
BootstrapNodes = ["enode://f47940a18bcb63740a795f057757560c60dffe07589766aabe665d92b8e5b808b7bd1103c70c44d25b5bd7ec21020f0883de4a06ade4277dff65a7b250e9c110@54.157.70.195:30301"]
BootstrapNodesV5 = ["enode://f47940a18bcb63740a795f057757560c60dffe07589766aabe665d92b8e5b808b7bd1103c70c44d25b5bd7ec21020f0883de4a06ade4277dff65a7b250e9c110@54.157.70.195:30301"]
StaticNodes = []
TrustedNodes = []
ListenAddr = ":31333"
EnableMsgEvents = false

[Dashboard]
Host = "localhost"
Port = 8080
Refresh = 5000000000
