---
- name: install docker
  sudo: true
  # install script from https://docs.docker.com/installation/ubuntulinux/
  shell: curl -sSL https://get.docker.com/ubuntu/ | sudo sh  

- name: install package dependencies
  sudo: true
  apt: name={{ item }}
  with_items:
      - python-pip

- name: install python dependencies
  sudo: true
  pip: name=docker-py


- name: enable docker for standard user
  sudo: true
  # todo: how to logout after this command, otherwise won't be effective in this play
  user: name=vagrant groups=docker append=yes

- name: checkout test repo
  git:
      repo: https://github.com/sveneh/tests.git 
      version: develop
      dest: git
