name: Build and Publish Docker image
on:
  workflow_dispatch:
  push:
    branches:
      - astria # Running this job only for astria branch
jobs:
  build-and-publish-latest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Checking out the repo
      - uses: actions/setup-go@v4
        with:
          go-version: "^1.20.x" # The Go version to download (if necessary) and use.
      - run: go version

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      # TODO - build for amd64 and arm64?
      # FIXME - version needs to be autoincrement, probably from git tags?
      - name: Build latest Docker image
        run: |
          docker build \
            --build-arg COMMIT=${GITHUB_SHA} \
            --build-arg VERSION=0.1 \
            --build-arg BUILDNUM=${GITHUB_RUN_NUMBER} \
            --tag ghcr.io/astriaorg/go-ethereum:latest .
      - name: Push latest Docker image
        run: docker push ghcr.io/astriaorg/go-ethereum:latest
