name: libevm delta

on:
  push:
    branches: [main, "release/**"]
  pull_request:
    branches: [main, "release/**"]
  workflow_dispatch:

jobs:
  diffs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # everything
          fetch-tags: true

      - name: Find base commit hash
        id: base-commit
        run: echo "LIBEVM_BASE=$(git rev-list --author "github-actions\[bot\]" --grep "rename Go module" -n 1 origin/main)" >> "$GITHUB_OUTPUT"

      - name: Color-blindness a11y
        run:
          | # https://davidmathlogic.com/colorblind/#%23D81B60-%231E88E5-%23FFC107-%23004D40:~:text=8%20pairs%20of%20contrasting%20colors
          git config color.diff.old "#DC3220";
          git config color.diff.new "#005AB5";

      - name: git diff ${{ steps.base-commit.outputs.LIBEVM_BASE }}
        run: |
          git diff --diff-filter=a --word-diff --unified=0 --color=always \
            ${{ steps.base-commit.outputs.LIBEVM_BASE }} \
            ':(exclude).golangci.yml' \
            ':(exclude).github/**' \
            ':(exclude)README.md';

      - name: git diff ${{ steps.base-commit.outputs.LIBEVM_BASE }}..main
        run: |
          git checkout main --;
          git diff --diff-filter=a --word-diff --unified=0 --color=always \
            "${{ steps.base-commit.outputs.LIBEVM_BASE }}" \
            ':(exclude).golangci.yml' \
            ':(exclude).github/**' \
            ':(exclude)README.md';
